---
- hosts: all
  become : true
  tasks:
  # any task name
  - name: Test Task
    # use file module to set the file state
    file:
      path: /home/cent/test.conf
      state: touch
      owner: cent
      group: cent
      mode: 0600
